import type { FoodItem } from './nutrition';

export const FOOD_DATABASE: FoodItem[] = [
  {
    id: 'f1',
    name: 'Arroz branco cozido',
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: 'f2',
    name: 'Feijão carioca cozido',
    calories: 76,
    protein: 4.8,
    carbs: 13.6,
    fat: 0.5,
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: 'f3',
    name: 'Peito de frango grelhado',
    calories: 159,
    protein: 32,
    carbs: 0,
    fat: 3.2,
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: 'f4',
    name: 'Ovo cozido',
    calories: 72,
    protein: 6.3,
    carbs: 0.4,
    fat: 4.8,
    servingSize: 1,
    servingUnit: 'un',
  },
  {
    id: 'f5',
    name: 'Banana prata',
    calories: 98,
    protein: 1.3,
    carbs: 26,
    fat: 0.1,
    servingSize: 1,
    servingUnit: 'un',
  },
  {
    id: 'f6',
    name: 'Batata doce cozida',
    calories: 77,
    protein: 0.6,
    carbs: 18.4,
    fat: 0.1,
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: 'f7',
    name: 'Whey Protein (dose)',
    calories: 120,
    protein: 24,
    carbs: 3,
    fat: 1.5,
    servingSize: 30,
    servingUnit: 'g',
  },
  {
    id: 'f8',
    name: 'Aveia em flocos',
    calories: 66,
    protein: 2.4,
    carbs: 11.5,
    fat: 1.4,
    servingSize: 20,
    servingUnit: 'g',
  },
  {
    id: 'f9',
    name: 'Pão francês',
    calories: 150,
    protein: 4.7,
    carbs: 29,
    fat: 1.6,
    servingSize: 1,
    servingUnit: 'un',
  },
  {
    id: 'f10',
    name: 'Queijo mussarela',
    calories: 72,
    protein: 5.5,
    carbs: 0.6,
    fat: 5.4,
    servingSize: 25,
    servingUnit: 'g',
  },
  {
    id: 'f11',
    name: 'Leite integral',
    calories: 124,
    protein: 6.2,
    carbs: 9.6,
    fat: 6.6,
    servingSize: 200,
    servingUnit: 'ml',
  },
  {
    id: 'f12',
    name: 'Iogurte natural',
    calories: 51,
    protein: 4.1,
    carbs: 5.2,
    fat: 1.5,
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: 'f13',
    name: 'Carne bovina (patinho)',
    calories: 169,
    protein: 32.4,
    carbs: 0,
    fat: 3.9,
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: 'f14',
    name: 'Macarrão cozido',
    calories: 102,
    protein: 3.4,
    carbs: 19.9,
    fat: 1.2,
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: 'f15',
    name: 'Abacate',
    calories: 96,
    protein: 1.2,
    carbs: 6,
    fat: 8.4,
    servingSize: 60,
    servingUnit: 'g',
  },
  {
    id: 'f16',
    name: 'Maçã',
    calories: 64,
    protein: 0.3,
    carbs: 17,
    fat: 0.1,
    servingSize: 1,
    servingUnit: 'un',
  },
  {
    id: 'f17',
    name: 'Amendoim torrado',
    calories: 142,
    protein: 6.4,
    carbs: 4.4,
    fat: 11.9,
    servingSize: 25,
    servingUnit: 'g',
  },
  {
    id: 'f18',
    name: 'Azeite de oliva',
    calories: 108,
    protein: 0,
    carbs: 0,
    fat: 12,
    servingSize: 12,
    servingUnit: 'ml',
  },
  {
    id: 'f19',
    name: 'Brócolis cozido',
    calories: 25,
    protein: 2.1,
    carbs: 4,
    fat: 0.2,
    servingSize: 80,
    servingUnit: 'g',
  },
  {
    id: 'f20',
    name: 'Mandioca cozida',
    calories: 125,
    protein: 0.6,
    carbs: 30.1,
    fat: 0.3,
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: 'f21',
    name: 'Salmão grelhado',
    calories: 182,
    protein: 27,
    carbs: 0,
    fat: 8.1,
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: 'f22',
    name: 'Atum em lata (light)',
    calories: 98,
    protein: 22,
    carbs: 0,
    fat: 0.8,
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: 'f23',
    name: 'Granola',
    calories: 142,
    protein: 3.2,
    carbs: 22,
    fat: 5,
    servingSize: 35,
    servingUnit: 'g',
  },
  {
    id: 'f24',
    name: 'Mel',
    calories: 64,
    protein: 0.1,
    carbs: 17.3,
    fat: 0,
    servingSize: 21,
    servingUnit: 'g',
  },
  {
    id: 'f25',
    name: 'Pasta de amendoim',
    calories: 94,
    protein: 4,
    carbs: 3,
    fat: 8,
    servingSize: 15,
    servingUnit: 'g',
  },
  {
    id: 'f26',
    name: 'Tomate',
    calories: 15,
    protein: 0.8,
    carbs: 3,
    fat: 0.1,
    servingSize: 80,
    servingUnit: 'g',
  },
  {
    id: 'f27',
    name: 'Alface',
    calories: 3,
    protein: 0.3,
    carbs: 0.4,
    fat: 0,
    servingSize: 20,
    servingUnit: 'g',
  },
  {
    id: 'f28',
    name: 'Tapioca',
    calories: 68,
    protein: 0,
    carbs: 17,
    fat: 0,
    servingSize: 20,
    servingUnit: 'g',
  },
  {
    id: 'f29',
    name: 'Cuscuz',
    calories: 112,
    protein: 1.5,
    carbs: 25,
    fat: 0.3,
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: 'f30',
    name: 'Frango desfiado',
    calories: 163,
    protein: 31,
    carbs: 0,
    fat: 3.5,
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: 'f31',
    name: 'Queijo cottage',
    calories: 42,
    protein: 6,
    carbs: 2.7,
    fat: 0.8,
    servingSize: 50,
    servingUnit: 'g',
  },
  {
    id: 'f32',
    name: 'Mamão papaia',
    calories: 40,
    protein: 0.5,
    carbs: 10.4,
    fat: 0.1,
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: 'f33',
    name: 'Laranja',
    calories: 47,
    protein: 1,
    carbs: 11.8,
    fat: 0.1,
    servingSize: 1,
    servingUnit: 'un',
  },
  {
    id: 'f34',
    name: 'Castanha do Pará',
    calories: 66,
    protein: 1.4,
    carbs: 1.2,
    fat: 6.7,
    servingSize: 10,
    servingUnit: 'g',
  },
  {
    id: 'f35',
    name: 'Requeijão cremoso',
    calories: 66,
    protein: 1.4,
    carbs: 0.8,
    fat: 6.5,
    servingSize: 20,
    servingUnit: 'g',
  },
  {
    id: 'f36',
    name: 'Carne moída refogada',
    calories: 212,
    protein: 26,
    carbs: 0,
    fat: 12,
    servingSize: 100,
    servingUnit: 'g',
  },
  {
    id: 'f37',
    name: 'Presunto',
    calories: 36,
    protein: 3.5,
    carbs: 0.7,
    fat: 2.2,
    servingSize: 25,
    servingUnit: 'g',
  },
  {
    id: 'f38',
    name: 'Açaí com granola',
    calories: 247,
    protein: 3.2,
    carbs: 42,
    fat: 8,
    servingSize: 200,
    servingUnit: 'g',
  },
  {
    id: 'f39',
    name: 'Café com leite',
    calories: 72,
    protein: 3.2,
    carbs: 6,
    fat: 3.8,
    servingSize: 200,
    servingUnit: 'ml',
  },
  {
    id: 'f40',
    name: 'Suco de laranja natural',
    calories: 94,
    protein: 1.4,
    carbs: 22,
    fat: 0.2,
    servingSize: 250,
    servingUnit: 'ml',
  },
];
