import {
  WorkoutPlan,
  WorkoutSession,
  PersonalRecord,
  ContentVideo,
  UserPreferences,
} from '../model/workout';
export const MOCK_USER: UserPreferences = {
  name: 'Atleta',
  goal: 'hipertrofia',
  experience: 'intermediario',
  preferredSplit: 'ppl',
  onboardingComplete: false,
};

export const MOCK_PLANS: WorkoutPlan[] = [
  {
    id: 'plan-1',
    name: 'PPL Hipertrofia',
    divisionType: 'ppl',
    daysPerWeek: 6,
    days: [
      {
        id: 'day-1',
        name: 'Push (Peito, Ombros, Tríceps)',
        exercises: [
          {
            id: 'pe-1',
            exerciseId: 'ex-01',
            sets: 4,
            repsMin: 6,
            repsMax: 10,
            technique: 'normal',
            restSeconds: 120,
            baseLoad: 80,
            order: 0,
          },
          {
            id: 'pe-2',
            exerciseId: 'ex-02',
            sets: 3,
            repsMin: 8,
            repsMax: 12,
            technique: 'rest-pause',
            restSeconds: 90,
            baseLoad: 30,
            order: 1,
          },
          {
            id: 'pe-3',
            exerciseId: 'ex-05',
            sets: 3,
            repsMin: 10,
            repsMax: 15,
            technique: 'drop-set',
            restSeconds: 60,
            baseLoad: 25,
            order: 2,
          },
          {
            id: 'pe-4',
            exerciseId: 'ex-14',
            sets: 4,
            repsMin: 12,
            repsMax: 15,
            technique: 'muscle-rounds',
            restSeconds: 10,
            baseLoad: 10,
            order: 3,
          },
          {
            id: 'pe-5',
            exerciseId: 'ex-23',
            sets: 3,
            repsMin: 10,
            repsMax: 15,
            technique: 'normal',
            restSeconds: 60,
            baseLoad: 30,
            order: 4,
          },
        ],
      },
      {
        id: 'day-2',
        name: 'Pull (Costas, Bíceps)',
        exercises: [
          {
            id: 'pe-6',
            exerciseId: 'ex-07',
            sets: 4,
            repsMin: 6,
            repsMax: 10,
            technique: 'normal',
            restSeconds: 120,
            order: 0,
          },
          {
            id: 'pe-7',
            exerciseId: 'ex-08',
            sets: 4,
            repsMin: 8,
            repsMax: 12,
            technique: 'normal',
            restSeconds: 90,
            baseLoad: 70,
            order: 1,
          },
          {
            id: 'pe-8',
            exerciseId: 'ex-09',
            sets: 3,
            repsMin: 10,
            repsMax: 12,
            technique: 'drop-set',
            restSeconds: 60,
            baseLoad: 55,
            order: 2,
          },
          {
            id: 'pe-9',
            exerciseId: 'ex-18',
            sets: 3,
            repsMin: 8,
            repsMax: 12,
            technique: 'rest-pause',
            restSeconds: 90,
            baseLoad: 30,
            order: 3,
          },
          {
            id: 'pe-10',
            exerciseId: 'ex-16',
            sets: 3,
            repsMin: 15,
            repsMax: 20,
            technique: 'normal',
            restSeconds: 60,
            baseLoad: 15,
            order: 4,
          },
        ],
      },
      {
        id: 'day-3',
        name: 'Legs (Pernas)',
        exercises: [
          {
            id: 'pe-11',
            exerciseId: 'ex-27',
            sets: 4,
            repsMin: 6,
            repsMax: 10,
            technique: 'normal',
            restSeconds: 180,
            baseLoad: 100,
            order: 0,
          },
          {
            id: 'pe-12',
            exerciseId: 'ex-28',
            sets: 4,
            repsMin: 8,
            repsMax: 12,
            technique: 'rest-pause',
            restSeconds: 120,
            baseLoad: 200,
            order: 1,
          },
          {
            id: 'pe-13',
            exerciseId: 'ex-30',
            sets: 3,
            repsMin: 10,
            repsMax: 15,
            technique: 'drop-set',
            restSeconds: 60,
            baseLoad: 50,
            order: 2,
          },
          {
            id: 'pe-14',
            exerciseId: 'ex-34',
            sets: 3,
            repsMin: 10,
            repsMax: 15,
            technique: 'normal',
            restSeconds: 60,
            baseLoad: 40,
            order: 3,
          },
          {
            id: 'pe-15',
            exerciseId: 'ex-39',
            sets: 4,
            repsMin: 12,
            repsMax: 20,
            technique: 'muscle-rounds',
            restSeconds: 10,
            baseLoad: 60,
            order: 4,
          },
        ],
      },
    ],
    createdAt: '2025-01-01',
    updatedAt: '2025-03-20',
  },
];

export const MOCK_SESSIONS: WorkoutSession[] = [
  {
    id: 'sess-1',
    planId: 'plan-1',
    dayId: 'day-1',
    dayName: 'Push',
    date: '2026-03-28',
    duration: 62,
    totalVolume: 12500,
    completed: true,
    exercises: [
      {
        exerciseId: 'ex-01',
        exerciseName: 'Supino Reto com Barra',
        sets: [
          { setNumber: 1, reps: 10, weight: 80, technique: 'normal' },
          { setNumber: 2, reps: 8, weight: 85, technique: 'normal' },
          { setNumber: 3, reps: 7, weight: 85, technique: 'normal' },
          { setNumber: 4, reps: 6, weight: 90, technique: 'normal', isPersonalRecord: true },
        ],
      },
      {
        exerciseId: 'ex-02',
        exerciseName: 'Supino Inclinado com Halteres',
        sets: [
          { setNumber: 1, reps: 12, weight: 30, technique: 'rest-pause', clusters: [8, 3, 1] },
          { setNumber: 2, reps: 10, weight: 30, technique: 'rest-pause', clusters: [7, 2, 1] },
        ],
      },
    ],
  },
  {
    id: 'sess-2',
    planId: 'plan-1',
    dayId: 'day-2',
    dayName: 'Pull',
    date: '2026-03-27',
    duration: 58,
    totalVolume: 11200,
    completed: true,
    exercises: [
      {
        exerciseId: 'ex-07',
        exerciseName: 'Barra Fixa',
        sets: [
          { setNumber: 1, reps: 10, weight: 0, technique: 'normal' },
          { setNumber: 2, reps: 8, weight: 0, technique: 'normal' },
          { setNumber: 3, reps: 7, weight: 0, technique: 'normal' },
        ],
      },
    ],
  },
  {
    id: 'sess-3',
    planId: 'plan-1',
    dayId: 'day-3',
    dayName: 'Legs',
    date: '2026-03-26',
    duration: 75,
    totalVolume: 18500,
    completed: true,
    exercises: [
      {
        exerciseId: 'ex-27',
        exerciseName: 'Agachamento Livre',
        sets: [
          { setNumber: 1, reps: 10, weight: 100, technique: 'normal' },
          { setNumber: 2, reps: 8, weight: 110, technique: 'normal' },
          { setNumber: 3, reps: 6, weight: 120, technique: 'normal', isPersonalRecord: true },
        ],
      },
    ],
  },
  {
    id: 'sess-4',
    planId: 'plan-1',
    dayId: 'day-1',
    dayName: 'Push',
    date: '2026-03-25',
    duration: 55,
    totalVolume: 11800,
    completed: true,
    exercises: [],
  },
  {
    id: 'sess-5',
    planId: 'plan-1',
    dayId: 'day-2',
    dayName: 'Pull',
    date: '2026-03-24',
    duration: 60,
    totalVolume: 10900,
    completed: true,
    exercises: [],
  },
];

export const MOCK_PRS: PersonalRecord[] = [
  {
    exerciseId: 'ex-01',
    exerciseName: 'Supino Reto com Barra',
    weight: 90,
    reps: 6,
    estimated1RM: 104,
    date: '2026-03-28',
  },
  {
    exerciseId: 'ex-27',
    exerciseName: 'Agachamento Livre',
    weight: 120,
    reps: 6,
    estimated1RM: 139,
    date: '2026-03-26',
  },
  {
    exerciseId: 'ex-36',
    exerciseName: 'Levantamento Terra',
    weight: 140,
    reps: 5,
    estimated1RM: 158,
    date: '2026-03-20',
  },
  {
    exerciseId: 'ex-08',
    exerciseName: 'Remada Curvada',
    weight: 75,
    reps: 8,
    estimated1RM: 93,
    date: '2026-03-22',
  },
];

export const MOCK_VIDEOS: ContentVideo[] = [
  {
    id: 'v-1',
    title: 'Rest-Pause: Como usar para máxima hipertrofia',
    creator: 'Garin',
    thumbnailUrl: 'https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg',
    youtubeId: 'dQw4w9WgXcQ',
    technique: 'rest-pause',
    muscleGroups: ['peito', 'costas'],
  },
  {
    id: 'v-2',
    title: 'Muscle Rounds: O protocolo completo',
    creator: 'Samuel Meller',
    thumbnailUrl: 'https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg',
    youtubeId: 'dQw4w9WgXcQ',
    technique: 'muscle-rounds',
    muscleGroups: ['ombros', 'panturrilhas'],
  },
  {
    id: 'v-3',
    title: 'Drop Sets: Quando e como aplicar',
    creator: 'Garin',
    thumbnailUrl: 'https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg',
    youtubeId: 'dQw4w9WgXcQ',
    technique: 'drop-set',
    muscleGroups: ['biceps', 'triceps'],
  },
  {
    id: 'v-4',
    title: 'Periodização para intermediários',
    creator: 'Leandro Twin',
    thumbnailUrl: 'https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg',
    youtubeId: 'dQw4w9WgXcQ',
    muscleGroups: ['peito', 'costas', 'quadriceps'],
  },
  {
    id: 'v-5',
    title: 'Técnica perfeita no Agachamento',
    creator: 'Samuel Meller',
    thumbnailUrl: 'https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg',
    youtubeId: 'dQw4w9WgXcQ',
    muscleGroups: ['quadriceps', 'gluteos'],
  },
  {
    id: 'v-6',
    title: 'Myo-Reps explicado em 10 minutos',
    creator: 'Garin',
    thumbnailUrl: 'https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg',
    youtubeId: 'dQw4w9WgXcQ',
    technique: 'myo-reps',
    muscleGroups: ['peito'],
  },
];

// Volume data for charts
export const MOCK_VOLUME_DATA = [
  { date: '03/17', volume: 9800 },
  { date: '03/18', volume: 11200 },
  { date: '03/19', volume: 0 },
  { date: '03/20', volume: 15600 },
  { date: '03/21', volume: 10500 },
  { date: '03/22', volume: 0 },
  { date: '03/23', volume: 0 },
  { date: '03/24', volume: 10900 },
  { date: '03/25', volume: 11800 },
  { date: '03/26', volume: 18500 },
  { date: '03/27', volume: 11200 },
  { date: '03/28', volume: 12500 },
  { date: '03/29', volume: 0 },
  { date: '03/30', volume: 0 },
];

export const MOCK_1RM_DATA = [
  { date: '03/01', supino: 95, agachamento: 125, terra: 148 },
  { date: '03/08', supino: 97, agachamento: 128, terra: 150 },
  { date: '03/15', supino: 100, agachamento: 132, terra: 153 },
  { date: '03/22', supino: 102, agachamento: 135, terra: 158 },
  { date: '03/28', supino: 104, agachamento: 139, terra: 158 },
];
